production:
  adapter: postgresql
  encoding: utf8
  host: db
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= Rails.application.credentials.dig(:database, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>
  pool: <%= ENV['DB_POOL'] %>
test:
  adapter: postgresql
  encoding: utf8
  host: db
  database: <%= ENV['POSTGRES_TEST'] %>
  username: <%= Rails.application.credentials.dig(:database, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>
development:
  adapter: postgresql
  encoding: utf8
  host: db
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= Rails.application.credentials.dig(:database, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>
  pool: <%= ENV['DB_POOL'] %>
