services:
  server:
    env_file:
      - ./.env
    build:
      context: ./
    volumes:
      # application mounts
      - ./:/usr/src/app:consistent
      # configuration mounts
      - ./db_buffer/:/tmp/backups/:cached
      - ${LOGS_LOCATION}:/usr/src/app/log/
      - bundle:/bundle
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    depends_on:
      - db

  db:
    env_file:
      - ./.env
    environment: 
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    image: postgres:9.5.5${ALPINE_SUFFIX}
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  db_volume:
  bundle:
