services:
  server:
    build:
      context: ./
    volumes:
      # application mounts
      - ./roadmap:/usr/src/app:consistent
      # configuration mounts
      - ./database.yml:/usr/src/app/config/database.yml:cached
      # other mounts
      - ./db_buffer/:/tmp/backups/:cached
      - ${LOGS_LOCATION}:/usr/src/app/log/
      - bundle:/bundle
   
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    env_file:
      - "./.env"
    
    depends_on:
      - db

  db:
    image: postgres:9.5.5${ALPINE_SUFFIX}
    volumes:
      - db_volume:/var/lib/postgresql/data
    env_file:
      - "./.env"
volumes:
  db_volume:
  bundle:
